# Generated by Django 4.0.6 on 2022-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='imgs/')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='servico',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
