# Generated by Django 4.0.6 on 2022-08-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0002_entrada_alter_servico_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='Entry',
        ),
    ]
