# Generated by Django 4.0.6 on 2022-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0006_alter_servico_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
