# Generated by Django 4.0.6 on 2022-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0010_alter_servico_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
