# Generated by Django 4.0.6 on 2022-11-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0013_entry_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
