# Generated by Django 4.0.6 on 2022-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0014_alter_servico_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
