# Generated by Django 4.0.6 on 2022-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farma_site_app', '0015_servico_position_alter_servico_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
