# Generated by Django 4.0.6 on 2022-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodia',
            name='farmacia_de_servico',
            field=models.CharField(choices=[('PI', 'Pisco'), ('RO', 'Roldão'), ('CR', 'Cruz Ferreira'), ('GI', 'Gil'), ('MA', 'Matilde Soares'), ('LA', 'Laura A. Leite'), ('NE', '-')], default='NE', max_length=2),
        ),
    ]
