# Generated by Django 4.0.6 on 2022-09-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_infodia_farmacia_de_servico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoDia',
            new_name='CalDia',
        ),
    ]
