# Generated by Django 4.0.6 on 2022-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_rename_infodia_caldia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldia',
            name='farmacia_de_servico',
            field=models.CharField(choices=[('Pisco', 'Pisco'), ('Roldão', 'Roldao'), ('CR', 'Cruz F'), ('GI', 'Gil'), ('MA', 'Matilde S'), ('LA', 'Laura A L'), ('NE', 'Nenhuma')], default='NE', max_length=20),
        ),
    ]
