# Generated by Django 4.0.6 on 2022-10-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_alter_caldia_farmacia_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldia',
            name='farmacia_de_servico',
            field=models.CharField(choices=[('Pisco', 'Pisco'), ('Roldão', 'Roldao'), ('C. Ferreira', 'Cruz F'), ('Gil', 'Gil'), ('M. Soares', 'Matilde S'), ('L.A. Leite', 'Laura A L'), ('-', 'Nenhuma')], default='-', max_length=20),
        ),
    ]
