# Generated by Django 4.0.6 on 2022-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_caldia_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='caldia',
            name='fds_excel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
