# Generated by Django 4.0.6 on 2022-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_caldia_fds_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldia',
            name='fds_excel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='caldia',
            name='info',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
