# Generated by Django 4.0.6 on 2022-10-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_alter_caldia_farmacia_de_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldia',
            name='info',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Outra informação'),
        ),
    ]
