# Generated by Django 4.0.6 on 2022-10-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_alter_caldia_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldia',
            name='farmacia_de_servico',
            field=models.CharField(choices=[('Pisco', 'Pisco'), ('Roldão', 'Roldao'), ('Cruz Ferreira', 'Cruz F'), ('Gil', 'Gil'), ('Matilde Soares', 'Matilde S'), ('Laura A. Leite', 'Laura A L'), ('-', 'Nenhuma'), ('0', 'Do Excel')], default='0', max_length=20, verbose_name='Farmácia'),
        ),
    ]
